language: rust

rust:
  - nightly
  - stable


cache:
  - cargo
  - apt

sudo: required

#
#before_script:
#  - rustup install stable-x86_64-unknown-linux-gnu

os:
  - linux

script:
  - cargo build --verbose
  - cargo build --features=no-std
  - cargo test --release
  - cargo bench

