language: rust

rust:
  - nightly
  - stable


cache:
  - cargo
  - apt

sudo: required

#
#before_script:
#  - rustup install stable-x86_64-unknown-linux-gnu

os:
  - linux

script:
  - cargo build --verbose
  - cargo build --features=no-std
  - cargo test --release

after_success:
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
    cargo bench;
    fi

