language: rust

rust:
  - nightly
  - stable


cache:
  - cargo
  - apt

sudo: required

before_script:
  - rustup target add thumbv7em-none-eabihf

os:
  - linux

script:
  - cargo build --verbose
  - cargo test --release
  - cargo build --features=no-std
  - cargo test --features=no-std --release

after_success:
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
      cargo bench;
      cargo build --features=no-std --target thumbv7em-none-eabihf;
    fi

